"""OpenAI-compatible Creative Writer Agent."""

from typing import Optional
import os

from agents.base_agent import BaseAgent, ContentRequest, ContentResult
from core.llm_client import LLMClient, LLMConfig


class OpenAIAgent(BaseAgent):
    """Creative content writer - works with ANY LLM (OpenAI, Ollama, LM Studio, etc.)."""
    
    @property
    def preferred_model(self) -> str:
        """Preferred LLM model for this agent."""
        return "gpt-4o" 
    
    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        model: Optional[str] = None,
        provider: Optional[str] = None,
    ):
        super().__init__(
            agent_id="openai-creative-writer",
            name="OpenAI Creative Writer",
            description="Creative content writer specializing in storytelling, blog posts",
            capabilities=["generate_creative", "write_blog", "storytelling"],
            skills=["creative-writing", "blog-writing", "storytelling"],
            api_key=api_key or os.getenv("OPENAI_API_KEY") or os.getenv("LLM_API_KEY"),
        )
        
        # Support any LLM via flexible configuration
        self.llm_config = LLMConfig.from_env()
        
        # Override with passed parameters
        if base_url:
            self.llm_config.base_url = base_url
        if model:
            self.llm_config.model = model
        if api_key:
            self.llm_config.api_key = api_key
        if provider:
            self.llm_config.provider = provider
        
        self._llm = None
    
    def _get_port(self) -> int:
        return 8001
    
    def _get_llm(self) -> LLMClient:
        """Get or create the flexible LLM client."""
        if self._llm is None:
            self._llm = LLMClient(self.llm_config)
        return self._llm
    
    def _generate_content(self, request: ContentRequest) -> ContentResult:
        """Generate creative content using flexible LLM."""
        
        llm = self._get_llm()
        prompt = self._build_prompt(request)
        
        # Try to generate with LLM
        if llm.is_available:
            try:
                content = llm.generate(
                    prompt=prompt,
                    system_prompt="You are a creative content writer specializing in engaging, high-quality content.",
                    temperature=0.8,
                    max_tokens=2000,
                )
                
                # Check for error response
                if content.startswith("Error:"):
                    return self._mock_response(prompt, request)
                
                return ContentResult(
                    content=content,
                    agent_id=self.agent_id,
                    quality_score=0.9,
                    metadata={
                        "model": self.llm_config.model,
                        "provider": self.llm_config.provider,
                    },
                )
            except Exception as e:
                return self._mock_response(prompt, request)
        else:
            # Use mock response in demo mode
            return self._mock_response(prompt, request)
    
    def _build_prompt(self, request: ContentRequest) -> str:
        """Build the prompt based on request."""
        base = f"Write a {request.length} {request.content_type} about {request.topic}."
        
        if request.style:
            base += f" Style: {request.style}."
        
        if request.context.get("audience"):
            base += f" Target audience: {request.context['audience']}."
        
        return base
    
    def _mock_response(self, prompt: str, request: ContentRequest) -> ContentResult:
        """Mock response for demo mode."""
        
        templates = {
            "blog": f"""# {request.topic.title()}

## Introduction

In today's rapidly evolving landscape, {request.topic} has emerged as a crucial area 
of focus for professionals and enthusiasts alike. This comprehensive exploration 
delves into the intricacies and nuances that make this subject so compelling.

## Key Insights

Our analysis reveals several pivotal aspects worth exploring:

1. **Understanding the Fundamentals** - Building a strong foundation
2. **Practical Applications** - Real-world implementations
3. **Future Implications** - What's on the horizon

## Conclusion

The journey through {request.topic} reveals both challenges and opportunities. 
As we continue to navigate these waters, staying informed and adaptable remains key.

---

*Generated by {self.name}*""",
            
            "storytelling": f"""# The Story of {request.topic.title()}

Once upon a time, in a world not so different from our own, there existed a topic 
that captivated the imagination of all who encountered it: {request.topic}.

The tale begins with humble origins, Growing from a simple idea into something 
extraordinary through the power of creativity and dedication.

*To be continued...*

---

*Generated by {self.name}*""",
        }
        
        template = templates.get(request.content_type, templates["blog"])
        
        return ContentResult(
            content=template,
            agent_id=self.agent_id,
            quality_score=0.85,
            metadata={"model": self.llm_config.model, "mock": True},
        )