"""Salesforce Sales Writer Agent."""

from typing import Optional
import os

from agents.base_agent import BaseAgent, ContentRequest, ContentResult


class SalesforceAgent(BaseAgent):
    """Sales and business content writer with Salesforce CRM integration.
    
    Preferred Model: gpt-4o (or any LLM via API)
    
    def __init__(
        self,
        client_id: Optional[str] = None,
        client_secret: Optional[str] = None,
        instance_url: Optional[str] = None,
    ):
        super().__init__(
            agent_id="salesforce-sales-writer",
            name="Salesforce Sales Writer",
            description="Sales and business content writer with CRM integration",
            capabilities=["sales_copy", "business_content", "crm_integration"],
            skills=["sales-writing", "business-writing", "crm-writing"],
            api_key=client_id or os.getenv("SALESFORCE_CLIENT_ID"),
        )
        self.client_secret = client_secret or os.getenv("SALESFORCE_CLIENT_SECRET")
        self.instance_url = instance_url or os.getenv("SALESFORCE_INSTANCE_URL")
        self._client = None
    
    def _get_port(self) -> int:
        return 8002
    
    def _get_client(self):
        """Get or create Salesforce client."""
        if self._client is None:
            try:
                from simple_salesforce import Salesforce
                self._client = Salesforce(
                    client_id=self.api_key,
                    client_secret=self.client_secret,
                    instance_url=self.instance_url,
                )
            except ImportError:
                self._client = None
        return self._client
    
    def _generate_content(self, request: ContentRequest) -> ContentResult:
        """Generate sales/business content."""
        client = self._get_client()
        
        # Build sales-focused prompt
        prompt = self._build_prompt(request)
        
        if client:
            try:
                # Use Salesforce Einstein AI if available
                # For now, use mock response as fallback
                return self._mock_response(prompt, request)
            except Exception:
                return self._mock_response(prompt, request)
        else:
            return self._mock_response(prompt, request)
    
    def _build_prompt(self, request: ContentRequest) -> str:
        """Build sales-focused prompt."""
        base = f"Write {request.length} sales copy for: {request.topic}."
        
        if request.context.get("product"):
            base += f" Product: {request.context['product']}."
        
        if request.context.get("cta"):
            base += f" Call to action: {request.context['cta']}."
        
        if request.context.get("target_audience"):
            base += f" Target: {request.context['target_audience']}."
        
        return base
    
    def _mock_response(self, prompt: str, request: ContentRequest) -> ContentResult:
        """Mock response for demo mode."""
        
        template = f"""# {request.topic.title()}

## Transform Your Business with {request.topic.title()}

Are you ready to take your business to the next level? Our innovative solution 
delivers results that matter.

### Why Choose Us?

✓ **Proven Results** - Backed by data and customer success stories
✓ **Expert Support** - Team of industry professionals
✓ **Scalable Solutions** - Growth with your business

### What Our Customers Say

> "This solution transformed our workflow and boosted productivity by 40%!" 
> — Happy Customer

### Get Started Today

Ready to experience the difference? Here's how to begin:

1. **Schedule a Demo** - See our solution in action
2. **Customized Plan** - Tailored to your needs  
3. **Success** - Achieve your goals

**Act Now! Limited time offer available.**

📞 Call: 1-800-SALES
🌐 Visit: www.example.com

---

*Generated by {self.name} (Salesforce CRM Integrated)*"""
        
        return ContentResult(
            content=template,
            agent_id=self.agent_id,
            quality_score=0.88,
            metadata={"provider": "salesforce", "crm_integrated": True},
        )
    
    async def get_crm_data(self, object_type: str, fields: list[str]) -> dict:
        """Get data from Salesforce CRM."""
        client = self._get_client()
        if not client:
            return {"error": "CRM not connected"}
        
        try:
            result = client.query_all(f"SELECT {','.join(fields)} FROM {object_type}")
            return {"data": result.get("records", [])}
        except Exception as e:
            return {"error": str(e)}